[DEFAULT]
# Name of the PDB file without .pdb extension
# The file should be located in the input_files directory
pdb_name = wt_delta

# Range of amino acid positions to process
# Format: comma-separated ranges (e.g., 1-4, 96-103, 105-150)
position_ranges = 7-13

# Enhanced mode flag
enhanced_mode = true

# Glycan model flag: select of glycans should be modeled or not (no_glycans, glycans)
glycan_model = glycans

#set the name of the rosetta docker container and rosetta version you installed
rosetta_docker_cont = rosettacommons/rosetta:ml

#set the RSMD filter value, any design with an RSMD greater than this value will be discarded
#a lower value is more stringent
RSMD_filter = 3

#set the number of structures to generate, usually 50 is a good number to get some diveristy 
nstruct = 15