[DEFAULT]
# Name of the PDB file without .pdb extension
# The file should be located in the input_files directory
pdb_name = r_WT_Mat_0001_0004

# Range of amino acid positions to process
# Format: comma-separated ranges (e.g., 1-4, 96-103, 105-150) will be processed as individual positions and processed separately
# or as grouped positions (e.g., [6,12,113]) will be processed as a group and processed together
# or as a combination of both (e.g., [6,12,113], 1-4, 96-103, 105-150) will be processed as a group and individual positions
# Please note that the script was only tested with individual positions, and the grouped positions are meant for visualisation purposes only.
# The analysis migth also not work with grouped positions.
position_ranges = 5-12

# Chain ID on which to specified positions are located
chain_id = A

# Enhanced mode flag
enhanced_mode = false

# Glycan model flag: select of glycans should be modeled or not (no_glycans, glycans)
glycan_model = no_glycans

#set the name of the rosetta docker container and rosetta version you installed
rosetta_docker_cont = rosettacommons/rosetta:ml

#set the RSMD filter value, any design with an RSMD greater than this value will be discarded
#a lower value is more stringent
RMSD_filter = 5

#set the number of structures to generate, usually 50 is a good number to get some diveristy 
nstruct = 5

# Optional: Number of CPU cores to use for parallel processing
# If not specified, will auto-detect and use 75% of available cores for system stability
# Example: ncores = 4 (to use 4 cores in parallel)
#ncores = 4